---

repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.7
        exclude: ^node_modules/

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.24.2
    hooks:
      - id: yamllint
        args: ['-d relaxed']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-json
      - id: check-merge-conflict

  - repo: https://github.com/PyCQA/isort
    rev: 5.4.2
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v7.9.0'
    hooks:
      - id: eslint
        args: ['--fix']
        files: \.jsx?$
        types: [file]
        additional_dependencies:
          - babel-eslint@10.1.0
          - eslint@7.8.1
          - eslint-config-airbnb@18.2.0
          - eslint-plugin-import@2.22.0
          - eslint-plugin-jsx-a11y@6.3.1
          - eslint-plugin-react@7.20.6
          - eslint-plugin-react-hooks@4.1.0
